In [2]:
### Importing the libraries ### 
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline
plt.rcParams['figure.figsize'] = (12.0 , 9.0)

In [3]:
### Importing The Dataset ### 
dataset = pd.read_csv('50_Startups.csv')
dataset.head()


R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
##Creating matrix of features
x = dataset.iloc[ : , : -1].values
## Creating Dependent Variable vector
y = dataset.iloc[ : , -1].values


In [5]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [6]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [7]:
### Encoding Categorical Data #### 

## Encoding the independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder' , OneHotEncoder() , [3])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
x


array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [9]:
### Spliting the dataset into the Training Set and Test Set ###
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 1)

In [10]:
x_test

array([[0.0, 0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [0.0, 0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [1.0, 0.0, 0.0, 28754.33, 118546.05, 172795.67],
       [0.0, 0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 0.0, 1.0, 542.05, 51743.15, 0.0],
       [0.0, 0.0, 1.0, 65605.48, 153032.06, 107138.38],
       [0.0, 1.0, 0.0, 1315.46, 115816.21, 297114.46],
       [0.0, 0.0, 1.0, 61136.38, 152701.92, 88218.23]], dtype=object)

In [11]:
### Feature Scaling ###
from sklearn.preprocessing import StandardScaler
ssc = StandardScaler()
x_train[ : , 3: ] = ssc.fit_transform(x_train[ : , 3: ])
x_test[ : , 3: ] = ssc.fit_transform(x_test[ : , 3: ])


In [12]:
x_train

array([[1.0, 0.0, 0.0, -0.32133038496226557, 0.18700266744239274,
        -1.3700842498314485],
       [1.0, 0.0, 0.0, -0.8955888632549127, -1.6137113933587277,
        -0.28442172627772067],
       [0.0, 0.0, 1.0, 0.024851552213493014, 1.1432479184934816,
        0.7660716916733844],
       [0.0, 1.0, 0.0, -1.124243352148879, 0.102749342455734,
        -0.06438621193773587],
       [0.0, 0.0, 1.0, 0.21041946816397103, 1.133148735616741,
        -1.758195776958278],
       [1.0, 0.0, 0.0, -1.2403142611108313, -1.0993455063779112,
        -0.5117896748200481],
       [1.0, 0.0, 0.0, -1.7866246546152684, -0.2895193240547929,
        -1.377766348852932],
       [0.0, 1.0, 0.0, -0.045874835892206874, 0.7679187112767512,
        -0.6292797489632387],
       [0.0, 1.0, 0.0, -0.07670896217898596, -0.06367998831873588,
        0.7962376091160044],
       [1.0, 0.0, 0.0, 0.3391969091012879, 0.43139962169069607,
        0.36964711927627536],
       [0.0, 1.0, 0.0, -1.1420564374940392, -1.5463881

In [13]:
x_test

array([[0.0, 0.0, 1.0, 0.2513334011762392, 0.5889703053597811,
        1.0279045230053547],
       [0.0, 0.0, 1.0, -0.2628037665160431, -0.7514947213553398,
        -0.11208849177028128],
       [1.0, 0.0, 0.0, -0.6028815991418002, 0.29723825358317,
        -0.36470435652588457],
       [0.0, 0.0, 1.0, -0.7708495697657277, -1.3494385149087984,
        -0.2684394970917044],
       [0.0, 1.0, 0.0, 1.853903310124685, -0.24751504007341874,
        1.450583933962291],
       [0.0, 0.0, 1.0, 1.6752094939630822, 0.3011766441088446,
        1.2596286459566892],
       [0.0, 0.0, 1.0, -1.1587647601853064, -1.7941441665088809,
        -1.6986988441155333],
       [0.0, 0.0, 1.0, 0.12321830310248519, 1.3768835242693027,
        -0.8715831627487197],
       [0.0, 1.0, 0.0, -1.1435258076588657, 0.2117758053112525,
        0.595045274722486],
       [0.0, 0.0, 1.0, 0.03516099490125036, 1.3665479102140872,
        -1.0176480253946951]], dtype=object)

In [14]:
### Training the Multiple linear Regression Model on the training set ###
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train , y_train)


LinearRegression()

In [15]:
### Predicting the test set results ###
y_pred = mlr.predict(x_test)
np.set_printoptions(precision= 3)
y_pred

array([126361.088, 105543.515,  92753.399,  88127.658, 182025.359,
       174938.854,  70325.686, 115354.543,  78536.175, 111904.799])

In [16]:
print(np.concatenate((y_pred.reshape(len(y_pred) , 1) , y_test.reshape(len(y_test),1)) , 1))

[[126361.088 105008.31 ]
 [105543.515  96479.51 ]
 [ 92753.399  78239.91 ]
 [ 88127.658  81229.06 ]
 [182025.359 191050.39 ]
 [174938.854 182901.99 ]
 [ 70325.686  35673.41 ]
 [115354.543 101004.64 ]
 [ 78536.175  49490.75 ]
 [111904.799  97483.56 ]]


In [17]:
### Making a Single Prediction ###
#ex (R&D Spend = 28754.33, Administration Spend = 118546.05 , Marketing Spend = 172795.67 and State = 'California')
print(mlr.predict([[1.0, 0.0, 0.0, -0.6028815991418002, 0.29723825358317, -0.36470435652588457]]))


[92753.399]


In [18]:
### Getting the final linear regression equation with the values of the coefficients ###

# In this case hypothesis equation , h = b0x0 + b1x1 + b2x2 + b3x3 + b4x4
# where x0 = State , x1 = R&D Spend , x2 = Administration , x3 = Marketing Spend , x4 = 1 and b4 = intercept
print(mlr.coef_)

[-2.852e+02  2.976e+02 -1.238e+01  3.351e+04 -2.425e+02  3.434e+03]


In [19]:
print(mlr.intercept_)

114564.78132777255


In [20]:
ans = mlr.predict(x_train)
ans

array([ 98762.253,  83684.211, 117738.475,  76944.37 , 115291.172,
        71227.431,  49751.277, 110978.085, 115041.506, 126810.355,
        75687.34 , 129921.028,  49479.617, 112608.525, 110240.443,
       169898.036,  98337.38 , 148949.079,  99680.661, 134630.563,
       102970.715,  66080.315,  90106.067, 128628.017, 116157.825,
       102294.062, 156091.376, 159019.397,  48270.777, 186863.182,
       116454.653, 190209.725, 144915.123, 161491.054, 133859.591,
       152846.316, 150770.522, 128837.658,  61653.87 ,  88888.38 ])

In [21]:
print(np.concatenate((ans.reshape(len(ans) , 1) , y_train.reshape(len(ans),1)) , 1))

[[ 98762.253  97427.84 ]
 [ 83684.211  81005.76 ]
 [117738.475 111313.02 ]
 [ 76944.37   90708.19 ]
 [115291.172 122776.86 ]
 [ 71227.431  71498.49 ]
 [ 49751.277  14681.4  ]
 [110978.085 105733.54 ]
 [115041.506 110352.25 ]
 [126810.355 134307.35 ]
 [ 75687.34   77798.83 ]
 [129921.028 125370.37 ]
 [ 49479.617  64926.08 ]
 [112608.525 108552.04 ]
 [110240.443 108733.99 ]
 [169898.036 166187.94 ]
 [ 98337.38   96778.92 ]
 [148949.079 132602.65 ]
 [ 99680.661  99937.59 ]
 [134630.563 146121.95 ]
 [102970.715 103282.38 ]
 [ 66080.315  65200.33 ]
 [ 90106.067  96712.8  ]
 [128628.017 124266.9  ]
 [116157.825 118474.03 ]
 [102294.062 107404.34 ]
 [156091.376 156122.51 ]
 [159019.397 155752.6  ]
 [ 48270.777  42559.73 ]
 [186863.182 191792.06 ]
 [116454.653 126992.93 ]
 [190209.725 192261.83 ]
 [144915.123 129917.04 ]
 [161491.054 156991.12 ]
 [133859.591 144259.4  ]
 [152846.316 149759.96 ]
 [150770.522 152211.77 ]
 [128837.658 141585.52 ]
 [ 61653.87   69758.98 ]
 [ 88888.38   89949.14 ]]